# Generated by Django 5.1.6 on 2025-02-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
